/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SafetyZonesRouteImport } from './routes/safety-zones'
import { Route as HealthInsightsRouteImport } from './routes/health-insights'
import { Route as FamilyGroupRouteImport } from './routes/family-group'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyZonesRoute = SafetyZonesRouteImport.update({
  id: '/safety-zones',
  path: '/safety-zones',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthInsightsRoute = HealthInsightsRouteImport.update({
  id: '/health-insights',
  path: '/health-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyGroupRoute = FamilyGroupRouteImport.update({
  id: '/family-group',
  path: '/family-group',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/family-group': typeof FamilyGroupRoute
  '/health-insights': typeof HealthInsightsRoute
  '/safety-zones': typeof SafetyZonesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/family-group': typeof FamilyGroupRoute
  '/health-insights': typeof HealthInsightsRoute
  '/safety-zones': typeof SafetyZonesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/family-group': typeof FamilyGroupRoute
  '/health-insights': typeof HealthInsightsRoute
  '/safety-zones': typeof SafetyZonesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/billing'
    | '/dashboard'
    | '/devices'
    | '/family-group'
    | '/health-insights'
    | '/safety-zones'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/billing'
    | '/dashboard'
    | '/devices'
    | '/family-group'
    | '/health-insights'
    | '/safety-zones'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/billing'
    | '/dashboard'
    | '/devices'
    | '/family-group'
    | '/health-insights'
    | '/safety-zones'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  DevicesRoute: typeof DevicesRoute
  FamilyGroupRoute: typeof FamilyGroupRoute
  HealthInsightsRoute: typeof HealthInsightsRoute
  SafetyZonesRoute: typeof SafetyZonesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-zones': {
      id: '/safety-zones'
      path: '/safety-zones'
      fullPath: '/safety-zones'
      preLoaderRoute: typeof SafetyZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-insights': {
      id: '/health-insights'
      path: '/health-insights'
      fullPath: '/health-insights'
      preLoaderRoute: typeof HealthInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-group': {
      id: '/family-group'
      path: '/family-group'
      fullPath: '/family-group'
      preLoaderRoute: typeof FamilyGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  DevicesRoute: DevicesRoute,
  FamilyGroupRoute: FamilyGroupRoute,
  HealthInsightsRoute: HealthInsightsRoute,
  SafetyZonesRoute: SafetyZonesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
